//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_WebNangCao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAUHOI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAUHOI()
        {
            this.DAPANs = new HashSet<DAPAN>();
            this.DANHSACHCAUHOIs = new HashSet<DANHSACHCAUHOI>();
        }
    
        public int IDCauHoi { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> IDLinhVuc { get; set; }
        public Nullable<int> IDLoaiCauHoi { get; set; }
    
        public virtual LINHVUC LINHVUC { get; set; }
        public virtual LOAICAUHOI LOAICAUHOI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAPAN> DAPANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHSACHCAUHOI> DANHSACHCAUHOIs { get; set; }
    }
}
