//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_WebNangCao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHSACHDAPANCHON
    {
        public int IDDethi { get; set; }
        public int IDDapAn { get; set; }
        public Nullable<int> ThuTu { get; set; }
    
        public virtual DAPAN DAPAN { get; set; }
        public virtual DETHI DETHI { get; set; }

        public static void Add_dap_an_chon_to_db(Quiz quiz, int id_de_thi, THITRACNGHIEMEntities db)
        {
            for(int order = 0; order < quiz.Id_dap_an_chons.Count; order++)
            {
                DANHSACHDAPANCHON dap_an_chon = new DANHSACHDAPANCHON();
                dap_an_chon.IDDethi = id_de_thi;
                dap_an_chon.IDDapAn = quiz.Id_dap_an_chons[order];
                dap_an_chon.ThuTu = order + 1;
                db.DANHSACHDAPANCHONs.Add(dap_an_chon);
                db.SaveChanges();
            }
        }
        
    }
}
