//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_WebNangCao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHSACHCAUHOI
    {
        public int IDDeThi { get; set; }
        public int IDCauHoi { get; set; }
        public Nullable<bool> KetQua { get; set; }
    
        public virtual CAUHOI CAUHOI { get; set; }
        public virtual DETHI DETHI { get; set; }
    }
}
