//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_WebNangCao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAPAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAPAN()
        {
            this.CT_DETHI = new HashSet<CT_DETHI>();
        }
    
        public int IDDapAn { get; set; }
        public int IDCauHoi { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> TinhChat { get; set; }
    
        public virtual CAUHOI CAUHOI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DETHI> CT_DETHI { get; set; }
    }
}
